### ISSUE TITLE
Font color of the selected line in command palette is too dark.

### ISSUE THREAD

**Issue by mhorniq** [shaodahong/theme-bear#1]
Selected element in command pallet is not very clearly readable because the font color is grey on teal or whatever color it is. See the image below.

![image](https://user-images.githubusercontent.com/5346720/36747680-eb80058e-1bf5-11e8-872d-2d073b3f2b80.png)

Great theme especially with Fira Code though. Thank you!

**Comment by shaodahong** [comment]
Thanks, I will solve it

**Comment by shaodahong** [comment]
Fix it，Please update version 0.0.6

**Comment by mhorniq** [comment]
Thank you for such a rapid fix! It is perfectly readable now.

![image](https://user-images.githubusercontent.com/5346720/36784363-6449d1c8-1c7f-11e8-9e7a-f19ff4520b6d.png)
