### ISSUE TITLE
font name

### ISSUE THREAD

**Issue by mdshemul48** [shaodahong/theme-bear#12]
hay there,
can you please tell me the font name that you used in the screenshot?

**Comment by mdshemul48** [comment]
I didn't saw the bottom that the font name was mentioned.. now i got it :3.. BTW thanks for the awesome theme..

**Comment by shaodahong** [comment]
> I didn't saw the bottom that the font name was mentioned.. now i got it :3.. BTW thanks for the awesome theme..

Thanks.
