### ISSUE TITLE
Focused selection in command panel is dark grey against slightly lighter grey

### ISSUE THREAD

**Issue by dpb06** [shaodahong/theme-bear#2]
Love the theme but found i needed to tinker to be able to see the selection that I made clearly for the command panel, (also like changing the auto complete highlight to orange too, but preference)

To see what I mean, view the command panel and have an option highlighted
then compare when the colours are customised to 
        "list.focusForeground": "#ff7c00", 
        "list.focusBackground": "#606c64"

![before-changes](https://user-images.githubusercontent.com/341625/38590063-6f38398e-3d1e-11e8-86c3-523103bb6086.png)

With customisation
![after-changes](https://user-images.githubusercontent.com/341625/38590066-754d75dc-3d1e-11e8-8b7e-ca8bdbe84912.png)

**Comment by shaodahong** [comment]
new version fix it
