### ISSUE TITLE
我装了Dank Mono这个字体，没有你这样的效果

### ISSUE THREAD

**Issue by brucmao** [shaodahong/theme-bear#5]
设置了
"editor.fontFamily": "Dank Mono",
但是没有你这样的效果，应该是没有用斜体，可以把你斜体的配置发一下吗
![image](https://user-images.githubusercontent.com/6119652/86525214-da0f9100-beb6-11ea-913b-9cff8e8f427a.png)

**Comment by shaodahong** [comment]
试试

```json
{
  "editor.fontFamily": "'DankMono-Regular'"
}
```

**Comment by brucmao** [comment]
> 试试
> 
> ```json
> {
>   "editor.fontFamily": "'DankMono-Regular'"
> }
> ```

![image](https://user-images.githubusercontent.com/6119652/86525422-79ce1e80-beb9-11ea-8e20-e6fff4ee1a21.png)
成这样了，还不如刚才好看

**Comment by shaodahong** [comment]
嗯，你这个没设置字体，用的默认的，我用的 Mac，看下字体库里面安装的字体名字

![image](https://user-images.githubusercontent.com/14831261/86525474-27413200-beba-11ea-8f5c-e598d84b829e.png)

Dank 提供 `Regular` 和 `Italic` 两种，我日常用的 `Regular`，演示用的 `Italic`

**Comment by shaodahong** [comment]
> 设置了
> "editor.fontFamily": "Dank Mono",
> 但是没有你这样的效果，应该是没有用斜体，可以把你斜体的配置发一下吗
> ![image](https://user-images.githubusercontent.com/6119652/86525214-da0f9100-beb6-11ea-913b-9cff8e8f427a.png)

你这个截图是用的 `Regular `, 你可以看到注视的 `s` 已经变了，要死全部都是斜体就要用到 `Italic `

**Comment by brucmao** [comment]
看下win10同时有 Dank Mono ltalic 和 Dank Mono Regular 
但是
指定"editor.fontFamily": "Dank Mono Regular",     有效果
指定"editor.fontFamily": "Dank Mono Italic",          无效果
现在的解决方法是删除Dank Mono Regular 然后指定
"editor.fontFamily": "Dank Mono",

**Comment by gandli** [comment]
> 设置了 "editor.fontFamily": "Dank Mono", 但是没有你这样的效果，应该是没有用斜体，可以把你斜体的配置发一下吗 ![image](https://user-images.githubusercontent.com/6119652/86525214-da0f9100-beb6-11ea-913b-9cff8e8f427a.png)

![reactjs](https://user-images.githubusercontent.com/85359251/187920919-d7625834-c549-457f-8537-af42c69e7e1e.png)

[让 Visual Studio Code 显示斜体字体](https://juejin.cn/post/7136578622106075149/)

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
      {
          "scope": [
              // the following elements will be in italic
              //   (=Fira Code iScript)
              "comment",
              "keyword.control.import.js", // import
              "keyword.control.export.js", // export
              "keyword.control.from.js", // from
              // "constant", // String, Number, Boolean…, this, super
              "storage.modifier", // static keyword
              "storage.type.class", // class keyword
              "storage.type.php", // typehints in methods keyword
              "keyword.other.new.php", // new
              "entity.other.attribute-name", // html attributes
              "fenced_code.block.language.markdown" // markdown language modifier
          ],
          "settings": {
              "fontStyle": "italic"
          }
      },
      {
          "scope": [
              // the following elements will be displayed in bold
              "entity.name.type.class" // class names
          ],
          "settings": {
              "fontStyle": "bold"
          }
      },
      {
          "scope": [
              // the following elements will be displayed in bold and italic
              "entity.name.section.markdown" // markdown headlines
          ],
          "settings": {
              "fontStyle": "italic bold"
          }
      },
      {
          "scope": [
              // the following elements will be excluded from italics 
              //   (VSCode has some defaults for italics)
              "invalid",
              "keyword.operator",
              "constant.numeric.css",
              "keyword.other.unit.px.css",
              "constant.numeric.decimal.js",
              "constant.numeric.json",
              "comment.block",
              "entity.other.attribute-name.class.css"
          ],
          "settings": {
              "fontStyle": ""
          }
      }
  ]
}
```
